# Generated by Django 2.2.12 on 2020-05-13 11:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_identifier', models.CharField(blank=True, max_length=7, null=True)),
                ('person_type', models.CharField(choices=[('Student', 'Student'), ('Professor', 'Professor'), ('Administrator', 'Administrator')], max_length=100)),
                ('person_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_identifier', models.CharField(blank=True, max_length=7, null=True)),
                ('resource_type', models.CharField(choices=[('Course', 'Course'), ('FDP', 'FDP'), ('Seminar', 'Seminar')], max_length=100)),
                ('resource_status', models.CharField(choices=[('Created', 'Created'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'Resource',
            },
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('CS', 'CS'), ('Civil', 'Civil'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical')], max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('resource_taken', models.ManyToManyField(to='all.Resource')),
                ('student_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_detail', to='all.Person')),
            ],
            options={
                'verbose_name_plural': 'StudentDetail',
            },
        ),
        migrations.CreateModel(
            name='SeminarDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('max_seats', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to='all.Person')),
                ('seminar_identifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seminar_detail', to='all.Resource')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='all.Person')),
                ('student_enrolled', models.ManyToManyField(to='all.Person')),
            ],
            options={
                'verbose_name_plural': 'SeminarDetail',
            },
        ),
        migrations.CreateModel(
            name='ProfessorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Civil', 'Civil'), ('Computer Science', 'Computer Science'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Metallurgy', 'Metallurgy')], max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('professor_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_detail', to='all.Person')),
                ('resource_undertaken', models.ManyToManyField(to='all.Resource')),
            ],
            options={
                'verbose_name_plural': 'ProfessorDetail',
            },
        ),
        migrations.CreateModel(
            name='PersonToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.Person')),
            ],
            options={
                'verbose_name_plural': 'PersonToken',
            },
        ),
        migrations.CreateModel(
            name='PersonPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=100)),
                ('password_open', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='all.Person')),
            ],
        ),
        migrations.CreateModel(
            name='FDPDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(choices=[('CS', 'CS'), ('Civil', 'Civil'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical')], max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('FDP_identifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FDP_detail', to='all.Resource')),
                ('co_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_tutor', to='all.Person')),
                ('student_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assigned', to='all.Person')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='all.Person')),
            ],
            options={
                'verbose_name_plural': 'FDPDetail',
            },
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(choices=[('CS', 'CS'), ('Civil', 'Civil'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical')], max_length=100)),
                ('course_credits', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('course_identifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_detail', to='all.Resource')),
                ('professor_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_1', to='all.Person')),
                ('professor_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_2', to='all.Person')),
                ('student_enrolled', models.ManyToManyField(to='all.Person')),
            ],
            options={
                'verbose_name_plural': 'CourseDetail',
            },
        ),
    ]
