# Generated by Django 2.2.12 on 2020-05-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetail',
            name='title',
        ),
        migrations.RemoveField(
            model_name='fdpdetail',
            name='title',
        ),
        migrations.RemoveField(
            model_name='seminardetail',
            name='title',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
