# Generated by Django 2.2.12 on 2020-05-13 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0002_auto_20200513_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetail',
            name='course_identifier',
        ),
        migrations.RemoveField(
            model_name='fdpdetail',
            name='FDP_identifier',
        ),
        migrations.RemoveField(
            model_name='professordetail',
            name='professor_identifier',
        ),
        migrations.RemoveField(
            model_name='seminardetail',
            name='seminar_identifier',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='student_identifier',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='course_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_title', to='all.Resource'),
        ),
        migrations.AddField(
            model_name='fdpdetail',
            name='FDP_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FDP_title', to='all.Resource'),
        ),
        migrations.AddField(
            model_name='professordetail',
            name='professor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_name', to='all.Person'),
        ),
        migrations.AddField(
            model_name='seminardetail',
            name='seminar_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='all.Resource'),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='student_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='all.Person'),
        ),
    ]
