# Generated by Django 2.2.12 on 2020-05-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0003_auto_20200513_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='course_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_detail', to='all.Resource'),
        ),
        migrations.AlterField(
            model_name='fdpdetail',
            name='FDP_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FDP_detail', to='all.Resource'),
        ),
        migrations.AlterField(
            model_name='professordetail',
            name='professor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_detail', to='all.Person'),
        ),
        migrations.AlterField(
            model_name='seminardetail',
            name='seminar_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seminar_detail', to='all.Resource'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='student_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_detail', to='all.Person'),
        ),
    ]
